Feature/scrapping
Vaipik/web_project_team_1 pull request #8
Opened 2023-02-04 12:14 UTC by Vishnyak13

Project for code rewiew, added next news:
1. Ukrainian news
2. Sport news
3. Tech news
4. Python book
5. Currency

URL main scrapping - http://127.0.0.1:8000/scrapping/

2023-02-04 15:27 UTC, Vaipik requested changes
Всі html файли мають наслідуватись від базового шаблона через {% extends 'base.html' %} 
все, що має бути відображено має знаходитись всередині {% block content %} {%endblock content %}

В урлах задай app_name = app_name, це по-перше, правильно, бо можливі конфлікти із назвами вьюшок серед інших апок і по-друге, хто зна як буде реалізовуватись профіль користувача)
Відповідно у основних урлах проекту слід додати namespace

views.py

URL слід винести кудись по типу libs.scrappy_urls.py і зробити з цього словник, де ключем буде категорія, а значення це буде список, з сайтів цієї категорії, навіть якщо посилання тільки одне. Відповідно response.request.get(URL[XXX]) має бути переробленим на звернення по ключу і т.д, бо можна змінити порядок і вьюшка зламається

headers теж мають бути винесені окремо, бо це дублювання коду.

Також вся логіка, що написано у вьюшках має бути винесена у окремий модуль. У джанго це прийнято називати services. і, наприклад, все з  get_news має бути замінено на щось типу 
context = get_new_context()
return render(request, template, context)
Якщо є можливість розбити той код, на ще більш менші функції, то слід робити, бо покрити тестами величезну функцію дуже складно, а навіть якщо покриється, то дуже незручно виявляти де сами падає, натомість малі функції більш зрозумілі та легше тестуються

requirements.txt 
це, в нашому випадку, зовсім непотрібний файл, бо ми користуємось poetry, де всі залежності, і навіть ті що виключно для розробки, вказані

config/urls.py && pyproject.toml
сюди ще має бути включений poetry.lock
Але перед тим, як безпосередньо пушити, слід повернутись на гілку main та зробити pull, щоб актуалізувати дані, далі повернутись на твою гілку та зробити git merge main і потім пушити.
Але в останньому я точно не впевнений,  але в тебе зараз виникає конфлікт, бо твої урли конфліктують з основними урлами оскільки не відповідають їм, так само як і pyproject.toml

2023-02-06 09:54 UTC, Vishnyak13 commented
Обновив проект

2023-02-06 12:41 UTC, Vaipik requested changes
.

2023-02-07 13:55 UTC, Vishnyak13 commented
Привіт. Запушив зміни, відписав у Slack про перелік змін.

2023-02-07 15:23 UTC, Vaipik requested changes
.

2023-02-09 13:01 UTC, Vishnyak13 commented
Привіт. Відписав у слак по змінах.

2023-02-10 09:07 UTC, Vaipik requested changes
.

2023-02-10 20:13 UTC, Vaipik approved these changes

2023-02-10 20:13 UTC, merged